name: deploy
on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    name: deploy test
    steps:
      - name: Hello world action step
        id: hello
        uses: 74th/workflow-permission-action@master
        with:
          users: 76th
          teams: 75th
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: deploy
        run: echo "deployed"
