name: deploy
on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    name: deploy test
    steps:
      - uses: actions/checkout@v2
      - name: check user permission
        id: hello
        uses: 74th/workflow-permission-action@master
        with:
          users: 76th
          listfile: .github/workflows/enables.txt
      - name: deploy
        run: echo "deployed"
